# Generated by Django 5.2.7 on 2025-12-16 21:32

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateTimeField(verbose_name="Date et heure prévues"),
                ),
                (
                    "actual_start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Heure de début réelle"
                    ),
                ),
                (
                    "actual_end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Heure de fin réelle"
                    ),
                ),
                (
                    "venue_name",
                    models.CharField(max_length=200, verbose_name="Nom du terrain"),
                ),
                (
                    "venue_address",
                    models.TextField(blank=True, verbose_name="Adresse du terrain"),
                ),
                (
                    "field_number",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Numéro de terrain"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Programmé"),
                            ("live", "En cours"),
                            ("half_time", "Mi-temps"),
                            ("finished", "Terminé"),
                            ("postponed", "Reporté"),
                            ("cancelled", "Annulé"),
                        ],
                        default="scheduled",
                        max_length=15,
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("group_stage", "Phase de groupes"),
                            ("knockout", "Élimination directe"),
                            ("friendly", "Match amical"),
                            ("final", "Finale"),
                            ("semi_final", "Demi-finale"),
                            ("quarter_final", "Quart de finale"),
                            ("third_place", "Match pour la 3ème place"),
                        ],
                        default="group_stage",
                        max_length=15,
                    ),
                ),
                ("home_score", models.PositiveIntegerField(default=0)),
                ("away_score", models.PositiveIntegerField(default=0)),
                ("home_score_half_time", models.PositiveIntegerField(default=0)),
                ("away_score_half_time", models.PositiveIntegerField(default=0)),
                (
                    "home_score_extra_time",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "away_score_extra_time",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "home_score_penalties",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "away_score_penalties",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "weather_conditions",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Conditions météo"
                    ),
                ),
                (
                    "attendance",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Nombre de spectateurs"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes du match")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Match",
                "verbose_name_plural": "Matchs",
                "db_table": "matches",
                "ordering": ["-scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="MatchEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("goal", "But"),
                            ("own_goal", "But contre son camp"),
                            ("penalty_goal", "But sur penalty"),
                            ("yellow_card", "Carton jaune"),
                            ("red_card", "Carton rouge"),
                            ("substitution", "Remplacement"),
                            ("injury", "Blessure"),
                            ("timeout", "Temps mort"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "minute",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(120),
                        ]
                    ),
                ),
                (
                    "additional_time",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Temps additionnel"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Description de l'événement"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Événement de match",
                "verbose_name_plural": "Événements de match",
                "db_table": "match_events",
                "ordering": ["minute", "additional_time", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="MatchLineup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("GK", "Gardien"),
                            ("RB", "Arrière droit"),
                            ("CB", "Défenseur central"),
                            ("LB", "Arrière gauche"),
                            ("CDM", "Milieu défensif"),
                            ("CM", "Milieu central"),
                            ("CAM", "Milieu offensif"),
                            ("RW", "Ailier droit"),
                            ("LW", "Ailier gauche"),
                            ("ST", "Attaquant"),
                            ("SUB", "Remplaçant"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "is_starter",
                    models.BooleanField(default=True, verbose_name="Titulaire"),
                ),
                (
                    "is_captain",
                    models.BooleanField(default=False, verbose_name="Capitaine"),
                ),
                ("minutes_played", models.PositiveIntegerField(default=0)),
                ("goals_scored", models.PositiveIntegerField(default=0)),
                ("assists", models.PositiveIntegerField(default=0)),
                ("yellow_cards", models.PositiveIntegerField(default=0)),
                ("red_cards", models.PositiveIntegerField(default=0)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Composition de match",
                "verbose_name_plural": "Compositions de match",
                "db_table": "match_lineups",
                "ordering": ["is_starter", "position"],
            },
        ),
        migrations.CreateModel(
            name="MatchReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField(verbose_name="Résumé du match")),
                (
                    "key_moments",
                    models.TextField(blank=True, verbose_name="Moments clés"),
                ),
                (
                    "referee_notes",
                    models.TextField(blank=True, verbose_name="Notes de l'arbitre"),
                ),
                (
                    "home_team_performance",
                    models.TextField(
                        blank=True, verbose_name="Performance équipe domicile"
                    ),
                ),
                (
                    "away_team_performance",
                    models.TextField(
                        blank=True, verbose_name="Performance équipe extérieure"
                    ),
                ),
                (
                    "incidents",
                    models.TextField(blank=True, verbose_name="Incidents particuliers"),
                ),
                (
                    "disciplinary_actions",
                    models.TextField(blank=True, verbose_name="Actions disciplinaires"),
                ),
                (
                    "field_conditions",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="État du terrain"
                    ),
                ),
                (
                    "weather_impact",
                    models.TextField(blank=True, verbose_name="Impact météorologique"),
                ),
                (
                    "is_validated",
                    models.BooleanField(default=False, verbose_name="Rapport validé"),
                ),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Rapport de match",
                "verbose_name_plural": "Rapports de match",
                "db_table": "match_reports",
            },
        ),
        migrations.CreateModel(
            name="MatchStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "possession_percentage",
                    models.PositiveIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("shots_total", models.PositiveIntegerField(default=0)),
                ("shots_on_target", models.PositiveIntegerField(default=0)),
                ("shots_off_target", models.PositiveIntegerField(default=0)),
                ("shots_blocked", models.PositiveIntegerField(default=0)),
                ("passes_total", models.PositiveIntegerField(default=0)),
                ("passes_completed", models.PositiveIntegerField(default=0)),
                (
                    "pass_accuracy",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("tackles_total", models.PositiveIntegerField(default=0)),
                ("tackles_won", models.PositiveIntegerField(default=0)),
                ("interceptions", models.PositiveIntegerField(default=0)),
                ("clearances", models.PositiveIntegerField(default=0)),
                ("fouls_committed", models.PositiveIntegerField(default=0)),
                ("fouls_suffered", models.PositiveIntegerField(default=0)),
                ("yellow_cards", models.PositiveIntegerField(default=0)),
                ("red_cards", models.PositiveIntegerField(default=0)),
                ("corners", models.PositiveIntegerField(default=0)),
                ("free_kicks", models.PositiveIntegerField(default=0)),
                ("offsides", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Statistiques de match",
                "verbose_name_plural": "Statistiques de match",
                "db_table": "match_statistics",
            },
        ),
    ]
