# Generated by Django 5.2.7 on 2025-12-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="round_number",
            field=models.PositiveIntegerField(default=1, help_text="Journée/Tour"),
        ),
    ]
