# Generated by Django 5.2.7 on 2026-01-09 02:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0003_add_round_number_to_match"),
        ("teams", "0004_add_default_venue_to_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchevent",
            name="player_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nom du joueur"
            ),
        ),
        migrations.AddField(
            model_name="matchevent",
            name="player_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Numéro du joueur"
            ),
        ),
        migrations.AlterField(
            model_name="matchevent",
            name="minute",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(120),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="matchevent",
            name="player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="teams.player",
            ),
        ),
    ]
