# Generated by Django 5.2.7 on 2025-12-16 21:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Nom du club"
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text="Ex: PSG, OM",
                        max_length=10,
                        unique=True,
                        verbose_name="Nom court",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="club_logos/"),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#000000",
                        help_text="Couleur principale (hex)",
                        max_length=7,
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#FFFFFF",
                        help_text="Couleur secondaire (hex)",
                        max_length=7,
                    ),
                ),
                ("address", models.TextField(verbose_name="Adresse")),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                (
                    "license_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Numéro de licence"
                    ),
                ),
                (
                    "founded_year",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1800),
                            django.core.validators.MaxValueValidator(2030),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Club",
                "verbose_name_plural": "Clubs",
                "db_table": "clubs",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                ("birth_date", models.DateField(verbose_name="Date de naissance")),
                (
                    "jersey_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(99),
                        ]
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("GB", "Goalkeeper"),
                            ("DG", "Left Back"),
                            ("DC", "Center Back"),
                            ("DD", "Right Back"),
                            ("MDC", "Defensive Mid"),
                            ("MC", "Central Mid"),
                            ("MD", "Right Mid"),
                            ("MG", "Left Mid"),
                            ("AD", "Right Winger"),
                            ("AG", "Left Winger"),
                            ("AC", "Striker"),
                            ("ATT", "Forward"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "is_captain",
                    models.BooleanField(default=False, verbose_name="Capitaine"),
                ),
                (
                    "is_main_player",
                    models.BooleanField(
                        default=False,
                        help_text="Fait partie des 11 joueurs principaux de l'équipe",
                        verbose_name="Joueur titulaire",
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True, help_text="Taille en cm", null=True
                    ),
                ),
                (
                    "weight",
                    models.PositiveIntegerField(
                        blank=True, help_text="Poids en kg", null=True
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="player_photos/"
                    ),
                ),
                ("goals_scored", models.PositiveIntegerField(default=0)),
                ("assists", models.PositiveIntegerField(default=0)),
                ("yellow_cards", models.PositiveIntegerField(default=0)),
                ("red_cards", models.PositiveIntegerField(default=0)),
                ("minutes_played", models.PositiveIntegerField(default=0)),
                (
                    "parent_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nom du parent/tuteur"
                    ),
                ),
                (
                    "parent_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone du parent"
                    ),
                ),
                (
                    "parent_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email du parent"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Joueur",
                "verbose_name_plural": "Joueurs",
                "db_table": "players",
                "ordering": ["team", "jersey_number"],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nom de l'équipe"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("u10", "U10"),
                            ("u11", "U11"),
                            ("u12", "U12"),
                            ("u13", "U13"),
                            ("u14", "U14"),
                            ("u15", "U15"),
                            ("u16", "U16"),
                            ("u17", "U17"),
                            ("u18", "U18"),
                            ("u19", "U19"),
                            ("u20", "U20"),
                            ("u21", "U21"),
                        ],
                        default="u13",
                        max_length=5,
                    ),
                ),
                (
                    "trophies_won",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Trophées remportés"
                    ),
                ),
                ("matches_played", models.PositiveIntegerField(default=0)),
                ("matches_won", models.PositiveIntegerField(default=0)),
                ("matches_drawn", models.PositiveIntegerField(default=0)),
                ("matches_lost", models.PositiveIntegerField(default=0)),
                ("goals_for", models.PositiveIntegerField(default=0)),
                ("goals_against", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Équipe",
                "verbose_name_plural": "Équipes",
                "db_table": "teams",
                "ordering": ["club__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="TeamStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("head_coach", "Entraîneur principal"),
                            ("assistant_coach", "Entraîneur adjoint"),
                            ("goalkeeper_coach", "Entraîneur des gardiens"),
                            ("physical_trainer", "Préparateur physique"),
                            ("physiotherapist", "Kinésithérapeute"),
                            ("manager", "Manager"),
                            ("doctor", "Médecin"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "license_level",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Niveau de licence"
                    ),
                ),
                (
                    "experience_years",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Années d'expérience"
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Spécialisation"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Date de début")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Date de fin"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Staff d'équipe",
                "verbose_name_plural": "Staff d'équipe",
                "db_table": "team_staff",
                "ordering": ["team", "role"],
            },
        ),
        migrations.CreateModel(
            name="TeamTournamentRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("confirmed", "Confirmée"),
                            ("rejected", "Refusée"),
                            ("withdrawn", "Retirée"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                ("confirmation_date", models.DateTimeField(blank=True, null=True)),
                (
                    "seed_number",
                    models.PositiveIntegerField(
                        blank=True, help_text="Tête de série", null=True
                    ),
                ),
                (
                    "special_requirements",
                    models.TextField(
                        blank=True, verbose_name="Exigences particulières"
                    ),
                ),
                ("tournament_points", models.PositiveIntegerField(default=0)),
                ("tournament_matches_played", models.PositiveIntegerField(default=0)),
                ("tournament_matches_won", models.PositiveIntegerField(default=0)),
                ("tournament_matches_drawn", models.PositiveIntegerField(default=0)),
                ("tournament_matches_lost", models.PositiveIntegerField(default=0)),
                ("tournament_goals_for", models.PositiveIntegerField(default=0)),
                ("tournament_goals_against", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Inscription de tournoi",
                "verbose_name_plural": "Inscriptions de tournoi",
                "db_table": "team_tournament_registrations",
                "ordering": ["-registration_date"],
            },
        ),
    ]
