# Generated by Django 5.2.7 on 2025-12-16 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0001_initial"),
        ("tournaments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_clubs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Propriétaire",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="assistant_coaches",
            field=models.ManyToManyField(
                blank=True,
                related_name="assistant_coached_teams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="teams.club",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="coach",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coached_teams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="followed_teams", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="teamstaff",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="teamstaff",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="teamtournamentregistration",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tournaments.tournamentgroup",
            ),
        ),
        migrations.AddField(
            model_name="teamtournamentregistration",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="teams.team"
            ),
        ),
        migrations.AddField(
            model_name="teamtournamentregistration",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tournaments.tournament"
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="tournaments",
            field=models.ManyToManyField(
                related_name="teams",
                through="teams.TeamTournamentRegistration",
                to="tournaments.tournament",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="player",
            unique_together={("team", "jersey_number")},
        ),
        migrations.AlterUniqueTogether(
            name="teamstaff",
            unique_together={("team", "user", "role")},
        ),
        migrations.AlterUniqueTogether(
            name="teamtournamentregistration",
            unique_together={("team", "tournament")},
        ),
        migrations.AlterUniqueTogether(
            name="team",
            unique_together={("club", "name", "category")},
        ),
    ]
