# Generated by Django 5.2.7 on 2025-12-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="parent2_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Email du 2ème parent"
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="parent2_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Nom du 2ème parent/tuteur"
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="parent2_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Téléphone du 2ème parent"
            ),
        ),
    ]
