# Generated by Django 5.2.7 on 2026-01-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_player_parent2_email_player_parent2_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="default_venue",
            field=models.CharField(
                blank=True,
                help_text="Nom du terrain où l'équipe joue habituellement",
                max_length=200,
                verbose_name="Terrain par défaut",
            ),
        ),
    ]
