# Generated by Django 5.2.7 on 2026-03-13 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0004_add_default_venue_to_team"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom du sport"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="sport_icons/",
                        verbose_name="Icône",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Sport",
                "verbose_name_plural": "Sports",
                "db_table": "sports",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="club",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="Ville"),
        ),
        migrations.AddField(
            model_name="club",
            name="discipline",
            field=models.CharField(
                default="Football",
                help_text="Discipline principale du club (ex: Football, Basket, Golf)",
                max_length=100,
                verbose_name="Discipline",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="address",
            field=models.TextField(blank=True, verbose_name="Adresse"),
        ),
        migrations.AddField(
            model_name="player",
            name="allergies",
            field=models.TextField(
                blank=True, verbose_name="Allergies / remarques médicales"
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="birth_place",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Lieu de naissance"
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="blood_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                max_length=3,
                verbose_name="Groupe sanguin",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="Ville"),
        ),
        migrations.AddField(
            model_name="player",
            name="digital_signature",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="signatures/",
                verbose_name="Signature digitale du parent",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="enrollment_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date d'inscription"
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="father_first_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Prénom du père"
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="father_last_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Nom du père"
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="image_authorization",
            field=models.BooleanField(
                default=False, verbose_name="Autorisation d'utilisation d'image"
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="medical_authorization",
            field=models.BooleanField(
                default=False, verbose_name="Autorisation médicale"
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="mother_first_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Prénom de la mère"
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="mother_last_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Nom de la mère"
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="nationality",
            field=models.CharField(
                blank=True,
                default="Marocaine",
                max_length=100,
                verbose_name="Nationalité",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="parental_authorization",
            field=models.BooleanField(
                default=False, verbose_name="Autorisation parentale"
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="phone_primary",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Téléphone principal"
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="phone_secondary",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Téléphone secondaire"
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="status",
            field=models.CharField(
                choices=[
                    ("actif", "Actif"),
                    ("suspendu", "Suspendu"),
                    ("sorti", "Sorti"),
                ],
                default="actif",
                max_length=10,
                verbose_name="Statut",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="transport_authorization",
            field=models.BooleanField(
                default=False, verbose_name="Autorisation de transport"
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="treating_doctor",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Médecin traitant"
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="address",
            field=models.TextField(blank=True, verbose_name="Adresse"),
        ),
        migrations.AlterField(
            model_name="player",
            name="parent2_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Email du 2ème parent (legacy)"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="parent2_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Nom du 2ème parent (legacy)"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="parent2_phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                verbose_name="Téléphone du 2ème parent (legacy)",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="parent_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Email du responsable légal"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="parent_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Nom du parent/tuteur (legacy)"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="parent_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Téléphone du parent (legacy)"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="player_photos/", verbose_name="Photo"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GB", "Gardien de but"),
                    ("DG", "Arrière gauche"),
                    ("DC", "Défenseur central"),
                    ("DD", "Arrière droit"),
                    ("MDC", "Milieu défensif central"),
                    ("MC", "Milieu central"),
                    ("MD", "Milieu droit"),
                    ("MG", "Milieu gauche"),
                    ("AD", "Ailier droit"),
                    ("AG", "Ailier gauche"),
                    ("AC", "Avant-centre"),
                    ("ATT", "Attaquant"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="category",
            field=models.CharField(
                choices=[
                    ("u6", "U6"),
                    ("u7", "U7"),
                    ("u8", "U8"),
                    ("u9", "U9"),
                    ("u10", "U10"),
                    ("u11", "U11"),
                    ("u12", "U12"),
                    ("u13", "U13"),
                    ("u14", "U14"),
                    ("u15", "U15"),
                    ("u16", "U16"),
                    ("u17", "U17"),
                    ("u18", "U18"),
                    ("u19", "U19"),
                    ("u20", "U20"),
                    ("u21", "U21"),
                    ("senior", "Senior"),
                    ("veteran", "Vétéran"),
                ],
                default="u13",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=20, verbose_name="Nom de la catégorie"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Description"
                    ),
                ),
                (
                    "min_age",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Âge minimum"
                    ),
                ),
                (
                    "max_age",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Âge maximum"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="teams.club",
                        verbose_name="Club",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
                "db_table": "categories",
                "ordering": ["club", "order", "name"],
                "unique_together": {("club", "name")},
            },
        ),
        migrations.AddField(
            model_name="player",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="players",
                to="teams.category",
                verbose_name="Catégorie",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="category_obj",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teams",
                to="teams.category",
                verbose_name="Catégorie (objet)",
            ),
        ),
        migrations.CreateModel(
            name="Coach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de naissance"
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nationalité"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="coach_photos/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("address", models.TextField(blank=True, verbose_name="Adresse")),
                ("diplomas", models.TextField(blank=True, verbose_name="Diplômes")),
                (
                    "certifications",
                    models.TextField(blank=True, verbose_name="Certifications"),
                ),
                (
                    "license_level",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Niveau de licence"
                    ),
                ),
                (
                    "experience_years",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Années d'expérience"
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Spécialisation"
                    ),
                ),
                (
                    "availabilities",
                    models.TextField(blank=True, verbose_name="Disponibilités"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coaches",
                        to="teams.club",
                        verbose_name="Club",
                    ),
                ),
                (
                    "supervised_categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="coaches",
                        to="teams.category",
                        verbose_name="Catégories encadrées",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coach_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur associé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coach",
                "verbose_name_plural": "Coachs",
                "db_table": "coaches",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom de la saison"),
                ),
                ("start_date", models.DateField(verbose_name="Date de début")),
                ("end_date", models.DateField(verbose_name="Date de fin")),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Saison active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasons",
                        to="teams.club",
                        verbose_name="Club",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saison",
                "verbose_name_plural": "Saisons",
                "db_table": "seasons",
                "ordering": ["-start_date"],
                "unique_together": {("club", "name")},
            },
        ),
        migrations.AddField(
            model_name="team",
            name="season",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teams",
                to="teams.season",
                verbose_name="Saison",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="sport",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clubs",
                to="teams.sport",
                verbose_name="Sport",
            ),
        ),
    ]
