# Generated by Django 5.2.7 on 2026-03-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0005_sport_club_city_club_discipline_player_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="father_first_name",
        ),
        migrations.RemoveField(
            model_name="player",
            name="father_last_name",
        ),
        migrations.RemoveField(
            model_name="player",
            name="mother_first_name",
        ),
        migrations.RemoveField(
            model_name="player",
            name="mother_last_name",
        ),
        migrations.RemoveField(
            model_name="player",
            name="parent2_email",
        ),
        migrations.RemoveField(
            model_name="player",
            name="parent2_name",
        ),
        migrations.RemoveField(
            model_name="player",
            name="parent2_phone",
        ),
        migrations.RemoveField(
            model_name="player",
            name="parent_email",
        ),
        migrations.RemoveField(
            model_name="player",
            name="parent_name",
        ),
        migrations.RemoveField(
            model_name="player",
            name="parent_phone",
        ),
        migrations.RemoveField(
            model_name="player",
            name="phone_primary",
        ),
        migrations.RemoveField(
            model_name="player",
            name="phone_secondary",
        ),
        migrations.AddField(
            model_name="player",
            name="father_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Email du père"
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="father_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Nom complet du père"
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="father_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Téléphone du père"
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="mother_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Email de la mère"
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="mother_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Nom complet de la mère"
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="mother_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Téléphone de la mère"
            ),
        ),
    ]
