# Generated by Django 5.2.7 on 2026-03-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0007_remove_coach_club_alter_season_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coach",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
    ]
