# Generated by Django 5.2.7 on 2026-03-18 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0008_alter_coach_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="sport",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teams",
                to="teams.sport",
                verbose_name="Sport",
            ),
        ),
    ]
