# Generated by Django 5.2.7 on 2026-03-19 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0009_team_sport"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="club",
            name="sport",
        ),
        migrations.AlterField(
            model_name="team",
            name="sport",
            field=models.CharField(
                choices=[
                    ("football", "Football"),
                    ("basketball", "Basketball"),
                    ("handball", "Handball"),
                    ("volleyball", "Volleyball"),
                    ("rugby", "Rugby"),
                    ("tennis", "Tennis"),
                    ("golf", "Golf"),
                    ("swimming", "Natation"),
                    ("athletics", "Athlétisme"),
                    ("other", "Autre"),
                ],
                default="football",
                max_length=20,
                verbose_name="Sport",
            ),
        ),
    ]
