# Generated by Django 5.2.7 on 2026-03-19 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0010_remove_club_sport_alter_team_sport"),
        ("tournaments", "0003_add_venues_to_tournament"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeasonTeamStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matches_played", models.PositiveIntegerField(default=0)),
                ("matches_won", models.PositiveIntegerField(default=0)),
                ("matches_drawn", models.PositiveIntegerField(default=0)),
                ("matches_lost", models.PositiveIntegerField(default=0)),
                ("goals_for", models.PositiveIntegerField(default=0)),
                ("goals_against", models.PositiveIntegerField(default=0)),
                (
                    "clean_sheets",
                    models.PositiveIntegerField(default=0, verbose_name="Clean sheets"),
                ),
                ("yellow_cards", models.PositiveIntegerField(default=0)),
                ("red_cards", models.PositiveIntegerField(default=0)),
                ("trophies_won", models.PositiveIntegerField(default=0)),
                (
                    "best_finish",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Meilleur résultat"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "season",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_stats",
                        to="teams.season",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="season_stats",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Statistiques d'équipe (saison)",
                "verbose_name_plural": "Statistiques d'équipe (saisons)",
                "db_table": "season_team_stats",
            },
        ),
        migrations.CreateModel(
            name="SeasonPlayerStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matches_played", models.PositiveIntegerField(default=0)),
                ("matches_started", models.PositiveIntegerField(default=0)),
                ("minutes_played", models.PositiveIntegerField(default=0)),
                ("goals_scored", models.PositiveIntegerField(default=0)),
                ("assists", models.PositiveIntegerField(default=0)),
                ("yellow_cards", models.PositiveIntegerField(default=0)),
                ("red_cards", models.PositiveIntegerField(default=0)),
                (
                    "average_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        verbose_name="Note moyenne",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="season_stats",
                        to="teams.player",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_stats",
                        to="teams.season",
                    ),
                ),
            ],
            options={
                "verbose_name": "Statistiques joueur (saison)",
                "verbose_name_plural": "Statistiques joueurs (saison)",
                "db_table": "season_player_stats",
                "ordering": ["-goals_scored", "-assists"],
                "unique_together": {("season", "player")},
            },
        ),
        migrations.CreateModel(
            name="SeasonTournamentResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "final_position",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Position finale"
                    ),
                ),
                (
                    "group_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Nom du groupe"
                    ),
                ),
                (
                    "group_position",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Position dans le groupe"
                    ),
                ),
                ("points", models.PositiveIntegerField(default=0)),
                ("matches_played", models.PositiveIntegerField(default=0)),
                ("matches_won", models.PositiveIntegerField(default=0)),
                ("matches_drawn", models.PositiveIntegerField(default=0)),
                ("matches_lost", models.PositiveIntegerField(default=0)),
                ("goals_for", models.PositiveIntegerField(default=0)),
                ("goals_against", models.PositiveIntegerField(default=0)),
                (
                    "is_champion",
                    models.BooleanField(default=False, verbose_name="Champion"),
                ),
                (
                    "trophy_name",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Vainqueur, Meilleure défense, Fair-play",
                        max_length=100,
                        verbose_name="Trophée",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_results",
                        to="teams.season",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="season_tournament_results",
                        to="teams.team",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="season_results",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "verbose_name": "Résultat tournoi (saison)",
                "verbose_name_plural": "Résultats tournois (saison)",
                "db_table": "season_tournament_results",
                "ordering": ["final_position"],
                "unique_together": {("season", "team", "tournament")},
            },
        ),
    ]
