# Generated by Django 5.2.7 on 2026-03-25 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0011_seasonteamstats_seasonplayerstats_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeasonPlayerRoster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("birth_date", models.DateField()),
                ("jersey_number", models.PositiveIntegerField()),
                ("position", models.CharField(blank=True, max_length=3)),
                ("is_captain", models.BooleanField(default=False)),
                ("is_main_player", models.BooleanField(default=False)),
                ("status", models.CharField(default="actif", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="season_rosters",
                        to="teams.player",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_roster",
                        to="teams.season",
                    ),
                ),
            ],
            options={
                "verbose_name": "Effectif saison",
                "verbose_name_plural": "Effectifs saison",
                "db_table": "season_player_roster",
                "ordering": ["jersey_number"],
                "unique_together": {("season", "player")},
            },
        ),
    ]
