# Generated by Django 5.2.7 on 2026-03-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("parent", "Parent"),
                    ("coach", "Coach"),
                    ("staff", "Staff"),
                    ("admin", "Admin/Organisateur"),
                    ("viewer", "Viewer"),
                ],
                max_length=10,
            ),
        ),
    ]
