# Generated by Django 5.2.7 on 2026-04-30 00:01

from django.db import migrations, models


def approve_existing_active_admins(apps, schema_editor):
    """Auto-approve existing active admin accounts so they aren't locked out."""
    User = apps.get_model("users", "User")
    User.objects.filter(user_type="admin", is_active=True).update(is_admin_approved=True)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_admin_approved",
            field=models.BooleanField(
                default=False,
                help_text="Required for admin/organizer accounts. Must be approved by UFootball team before login is allowed.",
            ),
        ),
        migrations.RunPython(
            approve_existing_active_admins,
            migrations.RunPython.noop,
        ),
    ]
