# Generated by Django 5.2.7 on 2025-12-16 21:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nom du tournoi"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "tournament_type",
                    models.CharField(
                        choices=[
                            ("league", "Championnat (Type Ligue)"),
                            ("group_knockout", "Groupes + Élimination"),
                        ],
                        default="league",
                        max_length=20,
                        verbose_name="Type de tournoi",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Date de début")),
                ("end_date", models.DateField(verbose_name="Date de fin")),
                ("location", models.CharField(max_length=200, verbose_name="Lieu")),
                (
                    "venue_address",
                    models.TextField(blank=True, verbose_name="Adresse complète"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "À venir"),
                            ("active", "En cours"),
                            ("finished", "Terminé"),
                            ("cancelled", "Annulé"),
                        ],
                        default="upcoming",
                        max_length=10,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("round_robin", "Round Robin"),
                            ("knockout", "Élimination directe"),
                            ("group_knockout", "Phase de groupes + Élimination"),
                            ("league", "Championnat"),
                        ],
                        default="group_knockout",
                        max_length=20,
                    ),
                ),
                (
                    "max_teams",
                    models.PositiveIntegerField(
                        default=16,
                        validators=[
                            django.core.validators.MinValueValidator(4),
                            django.core.validators.MaxValueValidator(64),
                        ],
                    ),
                ),
                (
                    "number_of_groups",
                    models.PositiveIntegerField(
                        default=4,
                        help_text="Seulement pour les tournois avec groupes",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(16),
                        ],
                    ),
                ),
                (
                    "teams_qualify_per_group",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Nombre d'équipes qualifiées par groupe",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(8),
                        ],
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="tournament_logos/"
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="tournament_banners/"
                    ),
                ),
                ("rules", models.TextField(blank=True, verbose_name="Règlement")),
                (
                    "prize_description",
                    models.TextField(blank=True, verbose_name="Prix et récompenses"),
                ),
                (
                    "registration_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                (
                    "match_duration",
                    models.PositiveIntegerField(
                        default=60, help_text="Durée en minutes"
                    ),
                ),
                (
                    "half_time_duration",
                    models.PositiveIntegerField(
                        default=10, help_text="Mi-temps en minutes"
                    ),
                ),
                ("points_per_win", models.PositiveIntegerField(default=3)),
                ("points_per_draw", models.PositiveIntegerField(default=1)),
                ("points_per_loss", models.PositiveIntegerField(default=0)),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="Tournoi public"),
                ),
                (
                    "registration_open",
                    models.BooleanField(
                        default=True, verbose_name="Inscriptions ouvertes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tournoi",
                "verbose_name_plural": "Tournois",
                "db_table": "tournaments",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="TournamentGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Nom du groupe")),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Groupe de tournoi",
                "verbose_name_plural": "Groupes de tournoi",
                "db_table": "tournament_groups",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TournamentNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "is_important",
                    models.BooleanField(
                        default=False, verbose_name="Annonce importante"
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Actualité de tournoi",
                "verbose_name_plural": "Actualités de tournoi",
                "db_table": "tournament_news",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TournamentPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "phase_type",
                    models.CharField(
                        choices=[
                            ("group_stage", "Phase de groupes"),
                            ("round_16", "Huitièmes de finale"),
                            ("quarter_final", "Quarts de finale"),
                            ("semi_final", "Demi-finales"),
                            ("final", "Finale"),
                            ("third_place", "Match pour la 3ème place"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Phase de tournoi",
                "verbose_name_plural": "Phases de tournoi",
                "db_table": "tournament_phases",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("match_date", models.DateTimeField(verbose_name="Date du match")),
                ("venue", models.CharField(blank=True, max_length=200)),
                ("home_score", models.PositiveIntegerField(default=0)),
                ("away_score", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Programmé"),
                            ("live", "En cours"),
                            ("finished", "Terminé"),
                            ("postponed", "Reporté"),
                            ("cancelled", "Annulé"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("match_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "round_number",
                    models.PositiveIntegerField(default=1, help_text="Journée/Tour"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "away_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_away_matches",
                        to="teams.team",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_home_matches",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Match",
                "verbose_name_plural": "Matches",
                "db_table": "tournament_matches",
                "ordering": ["match_date", "match_number"],
            },
        ),
        migrations.CreateModel(
            name="TeamGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(blank=True, null=True)),
                ("is_qualified", models.BooleanField(default=False)),
                (
                    "qualified_position",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_groups",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Équipe dans groupe",
                "verbose_name_plural": "Équipes dans groupes",
                "db_table": "team_groups",
                "ordering": ["position", "team__name"],
            },
        ),
    ]
