# Generated by Django 5.2.7 on 2025-12-16 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tournaments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organized_tournaments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="staff_members",
            field=models.ManyToManyField(
                blank=True,
                related_name="staff_tournaments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tournament_matches",
                to="tournaments.tournament",
            ),
        ),
        migrations.AddField(
            model_name="tournamentgroup",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="tournaments.tournament",
            ),
        ),
        migrations.AddField(
            model_name="teamgroup",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_groups",
                to="tournaments.tournamentgroup",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="tournaments.tournamentgroup",
            ),
        ),
        migrations.AddField(
            model_name="tournamentnews",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="tournamentnews",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news",
                to="tournaments.tournament",
            ),
        ),
        migrations.AddField(
            model_name="tournamentphase",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phases",
                to="tournaments.tournament",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="phase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="tournaments.tournamentphase",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tournamentgroup",
            unique_together={("tournament", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="teamgroup",
            unique_together={("team", "group")},
        ),
        migrations.AlterUniqueTogether(
            name="tournamentphase",
            unique_together={("tournament", "phase_type")},
        ),
    ]
