# Generated by Django 5.2.7 on 2026-01-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="venues",
            field=models.TextField(
                blank=True,
                help_text="Liste des terrains disponibles (un par ligne)",
                verbose_name="Terrains de compétition",
            ),
        ),
    ]
