# Generated by Django 5.2.7 on 2026-04-21 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0003_add_venues_to_tournament"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="away_team_placeholder",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Ex: 'Vainqueur QF2', 'Deuxième Groupe B'",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="bracket_position",
            field=models.PositiveIntegerField(
                blank=True, help_text="Position in the bracket (1, 2, 3...)", null=True
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="bracket_round",
            field=models.PositiveIntegerField(
                blank=True, help_text="Round number in the knockout bracket", null=True
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="home_team_placeholder",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Ex: 'Vainqueur QF1', 'Premier Groupe A'",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="is_third_place_match",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="match",
            name="next_match",
            field=models.ForeignKey(
                blank=True,
                help_text="Le vainqueur avance vers ce match",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_matches",
                to="tournaments.match",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="next_match_slot",
            field=models.CharField(
                blank=True,
                choices=[("home", "Domicile"), ("away", "Extérieur")],
                help_text="Le vainqueur sera placé en tant que domicile ou extérieur",
                max_length=4,
                null=True,
            ),
        ),
    ]
