# Generated by Django 5.2.7 on 2026-04-25 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0012_seasonplayerroster"),
        (
            "tournaments",
            "0004_match_away_team_placeholder_match_bracket_position_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="bracket_generated",
            field=models.BooleanField(
                default=False, verbose_name="Arbre éliminatoire généré"
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="number_of_legs",
            field=models.PositiveIntegerField(
                default=1, help_text="1 pour un aller simple, 2 pour aller-retour"
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="runner_up",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tournaments_runner_up",
                to="teams.team",
                verbose_name="Deuxième",
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="third_place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tournaments_third_place",
                to="teams.team",
                verbose_name="Troisième",
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="third_place_match",
            field=models.BooleanField(
                default=True, verbose_name="Jouer le match pour la 3ème place"
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tournaments_won",
                to="teams.team",
                verbose_name="Vainqueur",
            ),
        ),
    ]
