# Generated by Django 5.2.7 on 2026-03-13 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0005_sport_club_city_club_discipline_player_address_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("match", "Match"),
                            ("tournament", "Tournoi"),
                            ("event", "Événement"),
                            ("friendly", "Match amical"),
                            ("other", "Autre"),
                        ],
                        default="match",
                        max_length=15,
                        verbose_name="Type d'événement",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "opponent",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Adversaire"
                    ),
                ),
                ("location", models.CharField(max_length=200, verbose_name="Lieu")),
                ("date", models.DateField(verbose_name="Date")),
                ("start_time", models.TimeField(verbose_name="Heure de début")),
                (
                    "end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Heure de fin"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Planifié"),
                            ("cancelled", "Annulé"),
                            ("postponed", "Reporté"),
                            ("finished", "Terminé"),
                        ],
                        default="scheduled",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(
                        blank=True, verbose_name="Motif d'annulation/report"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="teams.season",
                        verbose_name="Saison",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="teams.team",
                        verbose_name="Équipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement",
                "verbose_name_plural": "Événements",
                "db_table": "planning_events",
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="TrainingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("start_time", models.TimeField(verbose_name="Heure de début")),
                ("end_time", models.TimeField(verbose_name="Heure de fin")),
                ("location", models.CharField(max_length=200, verbose_name="Lieu")),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Titre / thème"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "is_cancelled",
                    models.BooleanField(default=False, verbose_name="Annulé"),
                ),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, verbose_name="Motif d'annulation"),
                ),
                (
                    "recurrence",
                    models.CharField(
                        choices=[
                            ("none", "Aucune"),
                            ("weekly", "Hebdomadaire"),
                            ("biweekly", "Bi-hebdomadaire"),
                        ],
                        default="none",
                        max_length=10,
                        verbose_name="Récurrence",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_sessions",
                        to="teams.category",
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "coach",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_sessions",
                        to="teams.coach",
                        verbose_name="Coach responsable",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_training_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_sessions",
                        to="teams.season",
                        verbose_name="Saison",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_sessions",
                        to="teams.team",
                        verbose_name="Équipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Séance d'entraînement",
                "verbose_name_plural": "Séances d'entraînement",
                "db_table": "training_sessions",
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Convocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("convoque", "Convoqué"),
                            ("absent", "Absent"),
                            ("excuse", "Excusé"),
                            ("present", "Présent"),
                        ],
                        default="convoque",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "notified",
                    models.BooleanField(
                        default=False, verbose_name="Notification envoyée"
                    ),
                ),
                (
                    "notified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de notification"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="convocations",
                        to="teams.player",
                        verbose_name="Joueur",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="convocations",
                        to="planning.event",
                        verbose_name="Événement",
                    ),
                ),
                (
                    "training_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="convocations",
                        to="planning.trainingsession",
                        verbose_name="Séance d'entraînement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Convocation",
                "verbose_name_plural": "Convocations",
                "db_table": "convocations",
                "ordering": ["-created_at"],
            },
        ),
    ]
