# Generated by Django 5.2.7 on 2026-03-17 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="cancellation_reason",
        ),
    ]
