# Generated by Django 5.2.7 on 2026-03-19 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0002_remove_event_cancellation_reason"),
        ("teams", "0011_seasonteamstats_seasonplayerstats_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="convocation",
            options={
                "ordering": ["player__jersey_number"],
                "verbose_name": "Convocation",
                "verbose_name_plural": "Convocations",
            },
        ),
        migrations.AlterUniqueTogether(
            name="convocation",
            unique_together={("player", "event")},
        ),
        migrations.AddField(
            model_name="convocation",
            name="parent_response_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de réponse du parent"
            ),
        ),
        migrations.AlterField(
            model_name="convocation",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="convocations",
                to="planning.event",
                verbose_name="Événement",
            ),
        ),
        migrations.AlterField(
            model_name="convocation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("approved", "Approuvé"),
                    ("rejected", "Refusé"),
                ],
                default="pending",
                max_length=10,
                verbose_name="Statut",
            ),
        ),
        migrations.RemoveField(
            model_name="convocation",
            name="training_session",
        ),
    ]
